# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreisDB\ehpcalc_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EHPCalcDetail(object):
    def setupUi(self, EHPCalcDetail):
        EHPCalcDetail.setObjectName("EHPCalcDetail")
        EHPCalcDetail.resize(1293, 680)
        EHPCalcDetail.setMinimumSize(QtCore.QSize(1293, 680))
        EHPCalcDetail.setStyleSheet("*{\n"
"    font-family:segoe ui;\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"    background: yellow;\n"
"    width: 10px; /* when vertical */\n"
"    height: 10px; /* when horizontal */\n"
"}\n"
"\n"
"QWidget#centralwidget{\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QMenuBar{\n"
"    font-size:12px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"QMenu{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"    color: #000000;\n"
"    background-color: #d0d6da;\n"
"    border-style: none;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius: 5px;\n"
"    background-color: rgb(115, 127, 133);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"    width: 20px;\n"
"    border-style: 0px solid;\n"
"    border-radius: 1px;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"    width: 20px;\n"
"    border-style: solid;\n"
"    border-radius: 1px;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/up-arrow.png\');\n"
"    width: 7px;\n"
"    height: 7px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 7px;\n"
"    height: 7px;\n"
"}\n"
"\n"
"QLabel#lblTitle {\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QDateEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background: #d0d6da;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView:enabled {\n"
"    color: #000000;\n"
"    background: #e7eaec;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_navigationbar {\n"
"    color: #000000;\n"
"    background-color: #b8c0c6;\n"
"}\n"
"\n"
"\n"
"QTableView {\n"
"    font-size:12px;\n"
"    background: #ffffff;\n"
"    border-style: none;\n"
"    gridline-color: #737f86;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    color: #000000;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #b8c0c6;\n"
"    padding: 2px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #737f86;\n"
"    border-right: 1px solid #737f86;    \n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #737f86;\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border-left: 1px solid #737f86;\n"
"    border-right: 1px solid #737f86;\n"
"}\n"
"\n"
"\n"
"QListView{\n"
"    font-size:12px;\n"
"    color: #000000;\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListView::item \n"
"{\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QListView::item:hover \n"
"{\n"
"    background-color: #d0d6da;\n"
"    margin: 0px;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*STYLESHEET FÜR QFrame*/\n"
"\n"
"QFrame#fraSideMenu, QFrame#fraTable, QFrame#fraTitle, QFrame#fraFooter {\n"
"    border-radius: 20px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QGridLayout*/\n"
"\n"
"QGridLayout {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QLabel*/\n"
"\n"
"QLabel {\n"
"    border-radius: 0px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QComboBox*/\n"
"\n"
"QComboBox {\n"
"    font-size:12px;\n"
"    border: solid;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background: #d0d6da;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on {\n"
"    background:#a1abb1;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 0px;\n"
"    background: #ffffff;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(EHPCalcDetail)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fraFooter = QtWidgets.QFrame(self.centralwidget)
        self.fraFooter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraFooter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraFooter.setObjectName("fraFooter")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.fraFooter)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lblLabel12 = QtWidgets.QLabel(self.fraFooter)
        self.lblLabel12.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.lblLabel12.setFont(font)
        self.lblLabel12.setObjectName("lblLabel12")
        self.gridLayout_9.addWidget(self.lblLabel12, 1, 0, 1, 1)
        self.lblLabel11 = QtWidgets.QLabel(self.fraFooter)
        self.lblLabel11.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.lblLabel11.setFont(font)
        self.lblLabel11.setObjectName("lblLabel11")
        self.gridLayout_9.addWidget(self.lblLabel11, 0, 0, 1, 1)
        self.lblProgrammname = QtWidgets.QLabel(self.fraFooter)
        self.lblProgrammname.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblProgrammname.setFont(font)
        self.lblProgrammname.setObjectName("lblProgrammname")
        self.gridLayout_9.addWidget(self.lblProgrammname, 0, 1, 1, 1)
        self.lblVersion = QtWidgets.QLabel(self.fraFooter)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblVersion.setFont(font)
        self.lblVersion.setObjectName("lblVersion")
        self.gridLayout_9.addWidget(self.lblVersion, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraFooter, 2, 0, 1, 2)
        self.fraTitle = QtWidgets.QFrame(self.centralwidget)
        self.fraTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTitle.setObjectName("fraTitle")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.fraTitle)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblTitle = QtWidgets.QLabel(self.fraTitle)
        self.lblTitle.setMinimumSize(QtCore.QSize(200, 30))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("")
        self.lblTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout_7.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraTitle, 0, 0, 1, 2)
        self.fraTable = QtWidgets.QFrame(self.centralwidget)
        self.fraTable.setMinimumSize(QtCore.QSize(400, 300))
        self.fraTable.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.fraTable.setObjectName("fraTable")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fraTable)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cmdNewPos = QtWidgets.QPushButton(self.fraTable)
        self.cmdNewPos.setMinimumSize(QtCore.QSize(145, 25))
        self.cmdNewPos.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdNewPos.setFont(font)
        self.cmdNewPos.setStyleSheet("")
        self.cmdNewPos.setObjectName("cmdNewPos")
        self.gridLayout_4.addWidget(self.cmdNewPos, 5, 6, 1, 1)
        self.lblLabel1 = QtWidgets.QLabel(self.fraTable)
        self.lblLabel1.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLabel1.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel1.setFont(font)
        self.lblLabel1.setToolTipDuration(0)
        self.lblLabel1.setObjectName("lblLabel1")
        self.gridLayout_4.addWidget(self.lblLabel1, 0, 0, 1, 1)
        self.txtID = QtWidgets.QLineEdit(self.fraTable)
        self.txtID.setMinimumSize(QtCore.QSize(5, 25))
        self.txtID.setMaximumSize(QtCore.QSize(205, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.txtID.setFont(font)
        self.txtID.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.txtID.setObjectName("txtID")
        self.gridLayout_4.addWidget(self.txtID, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 4, 1, 3)
        self.cboLG = QtWidgets.QComboBox(self.fraTable)
        self.cboLG.setMinimumSize(QtCore.QSize(111, 25))
        self.cboLG.setMaximumSize(QtCore.QSize(240, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cboLG.setFont(font)
        self.cboLG.setStyleSheet("")
        self.cboLG.setEditable(False)
        self.cboLG.setObjectName("cboLG")
        self.gridLayout_4.addWidget(self.cboLG, 1, 1, 1, 1)
        self.txtPos = QtWidgets.QLineEdit(self.fraTable)
        self.txtPos.setMinimumSize(QtCore.QSize(300, 25))
        self.txtPos.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.txtPos.setFont(font)
        self.txtPos.setObjectName("txtPos")
        self.gridLayout_4.addWidget(self.txtPos, 1, 2, 1, 1)
        self.cmdSave = QtWidgets.QPushButton(self.fraTable)
        self.cmdSave.setMinimumSize(QtCore.QSize(145, 25))
        self.cmdSave.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdSave.setFont(font)
        self.cmdSave.setStyleSheet("")
        self.cmdSave.setObjectName("cmdSave")
        self.gridLayout_4.addWidget(self.cmdSave, 5, 7, 1, 1)
        self.lblLabel4_3 = QtWidgets.QLabel(self.fraTable)
        self.lblLabel4_3.setMinimumSize(QtCore.QSize(150, 20))
        self.lblLabel4_3.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel4_3.setFont(font)
        self.lblLabel4_3.setObjectName("lblLabel4_3")
        self.gridLayout_4.addWidget(self.lblLabel4_3, 0, 7, 1, 1)
        self.cboEinheit = QtWidgets.QComboBox(self.fraTable)
        self.cboEinheit.setMinimumSize(QtCore.QSize(111, 25))
        self.cboEinheit.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cboEinheit.setFont(font)
        self.cboEinheit.setStyleSheet("")
        self.cboEinheit.setEditable(False)
        self.cboEinheit.setObjectName("cboEinheit")
        self.gridLayout_4.addWidget(self.cboEinheit, 1, 3, 1, 1)
        self.lblLabel4_2 = QtWidgets.QLabel(self.fraTable)
        self.lblLabel4_2.setMinimumSize(QtCore.QSize(75, 20))
        self.lblLabel4_2.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel4_2.setFont(font)
        self.lblLabel4_2.setObjectName("lblLabel4_2")
        self.gridLayout_4.addWidget(self.lblLabel4_2, 0, 3, 1, 1)
        self.lblLabel1_3 = QtWidgets.QLabel(self.fraTable)
        self.lblLabel1_3.setMinimumSize(QtCore.QSize(240, 20))
        self.lblLabel1_3.setMaximumSize(QtCore.QSize(240, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel1_3.setFont(font)
        self.lblLabel1_3.setToolTipDuration(0)
        self.lblLabel1_3.setObjectName("lblLabel1_3")
        self.gridLayout_4.addWidget(self.lblLabel1_3, 0, 1, 1, 1)
        self.lblLabel1_2 = QtWidgets.QLabel(self.fraTable)
        self.lblLabel1_2.setMinimumSize(QtCore.QSize(300, 20))
        self.lblLabel1_2.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel1_2.setFont(font)
        self.lblLabel1_2.setToolTipDuration(0)
        self.lblLabel1_2.setObjectName("lblLabel1_2")
        self.gridLayout_4.addWidget(self.lblLabel1_2, 0, 2, 1, 1)
        self.lblLabel1_5 = QtWidgets.QLabel(self.fraTable)
        self.lblLabel1_5.setMinimumSize(QtCore.QSize(0, 20))
        self.lblLabel1_5.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel1_5.setFont(font)
        self.lblLabel1_5.setToolTipDuration(0)
        self.lblLabel1_5.setObjectName("lblLabel1_5")
        self.gridLayout_4.addWidget(self.lblLabel1_5, 4, 0, 1, 1)
        self.grdEHPDetail = QtWidgets.QTableWidget(self.fraTable)
        self.grdEHPDetail.setMinimumSize(QtCore.QSize(400, 300))
        self.grdEHPDetail.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.grdEHPDetail.setFont(font)
        self.grdEHPDetail.setAutoFillBackground(False)
        self.grdEHPDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.grdEHPDetail.setLineWidth(0)
        self.grdEHPDetail.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.grdEHPDetail.setRowCount(0)
        self.grdEHPDetail.setColumnCount(0)
        self.grdEHPDetail.setObjectName("grdEHPDetail")
        self.grdEHPDetail.horizontalHeader().setCascadingSectionResizes(True)
        self.grdEHPDetail.horizontalHeader().setMinimumSectionSize(20)
        self.grdEHPDetail.horizontalHeader().setSortIndicatorShown(True)
        self.grdEHPDetail.horizontalHeader().setStretchLastSection(True)
        self.grdEHPDetail.verticalHeader().setVisible(False)
        self.grdEHPDetail.verticalHeader().setDefaultSectionSize(20)
        self.grdEHPDetail.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_4.addWidget(self.grdEHPDetail, 2, 0, 1, 8)
        self.cmdDelete = QtWidgets.QPushButton(self.fraTable)
        self.cmdDelete.setMinimumSize(QtCore.QSize(145, 25))
        self.cmdDelete.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdDelete.setFont(font)
        self.cmdDelete.setStyleSheet("")
        self.cmdDelete.setObjectName("cmdDelete")
        self.gridLayout_4.addWidget(self.cmdDelete, 5, 5, 1, 1)
        self.datPBBis = QtWidgets.QDateEdit(self.fraTable)
        self.datPBBis.setMinimumSize(QtCore.QSize(145, 25))
        self.datPBBis.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.datPBBis.setFont(font)
        self.datPBBis.setCalendarPopup(True)
        self.datPBBis.setObjectName("datPBBis")
        self.gridLayout_4.addWidget(self.datPBBis, 1, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 5, 4, 1, 1)
        self.txtErgebnis = QtWidgets.QLineEdit(self.fraTable)
        self.txtErgebnis.setMinimumSize(QtCore.QSize(150, 25))
        self.txtErgebnis.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.txtErgebnis.setFont(font)
        self.txtErgebnis.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtErgebnis.setObjectName("txtErgebnis")
        self.gridLayout_4.addWidget(self.txtErgebnis, 3, 7, 1, 1)
        self.txtAnmerkungen = QtWidgets.QLineEdit(self.fraTable)
        self.txtAnmerkungen.setMinimumSize(QtCore.QSize(1158, 25))
        self.txtAnmerkungen.setMaximumSize(QtCore.QSize(6000, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.txtAnmerkungen.setFont(font)
        self.txtAnmerkungen.setObjectName("txtAnmerkungen")
        self.gridLayout_4.addWidget(self.txtAnmerkungen, 4, 1, 1, 7)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraTable, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        EHPCalcDetail.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EHPCalcDetail)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1293, 21))
        self.menubar.setObjectName("menubar")
        EHPCalcDetail.setMenuBar(self.menubar)

        self.retranslateUi(EHPCalcDetail)
        QtCore.QMetaObject.connectSlotsByName(EHPCalcDetail)

    def retranslateUi(self, EHPCalcDetail):
        _translate = QtCore.QCoreApplication.translate
        EHPCalcDetail.setWindowTitle(_translate("EHPCalcDetail", "MainWindow"))
        self.lblLabel12.setText(_translate("EHPCalcDetail", "Version:"))
        self.lblLabel11.setText(_translate("EHPCalcDetail", "Programmname:"))
        self.lblProgrammname.setText(_translate("EHPCalcDetail", "Version"))
        self.lblVersion.setText(_translate("EHPCalcDetail", "Version"))
        self.lblTitle.setText(_translate("EHPCalcDetail", "Dateiname"))
        self.cmdNewPos.setText(_translate("EHPCalcDetail", "Neue benutzerdef. Pos."))
        self.lblLabel1.setToolTip(_translate("EHPCalcDetail", "<html><head/><body><p>Durch das setzen von &quot;/&quot; können mehrere Teilbegriffe gesucht werden.</p></body></html>"))
        self.lblLabel1.setText(_translate("EHPCalcDetail", "ID:"))
        self.cmdSave.setText(_translate("EHPCalcDetail", "Speichern"))
        self.lblLabel4_3.setText(_translate("EHPCalcDetail", "Preisbasis:"))
        self.lblLabel4_2.setText(_translate("EHPCalcDetail", "Einheit:"))
        self.lblLabel1_3.setToolTip(_translate("EHPCalcDetail", "<html><head/><body><p>Durch das setzen von &quot;/&quot; können mehrere Teilbegriffe gesucht werden.</p></body></html>"))
        self.lblLabel1_3.setText(_translate("EHPCalcDetail", "LG:"))
        self.lblLabel1_2.setToolTip(_translate("EHPCalcDetail", "<html><head/><body><p>Durch das setzen von &quot;/&quot; können mehrere Teilbegriffe gesucht werden.</p></body></html>"))
        self.lblLabel1_2.setText(_translate("EHPCalcDetail", "Position:"))
        self.lblLabel1_5.setToolTip(_translate("EHPCalcDetail", "<html><head/><body><p>Durch das setzen von &quot;/&quot; können mehrere Teilbegriffe gesucht werden.</p></body></html>"))
        self.lblLabel1_5.setText(_translate("EHPCalcDetail", "Anmerkung:"))
        self.grdEHPDetail.setSortingEnabled(True)
        self.cmdDelete.setText(_translate("EHPCalcDetail", "Löschen"))
