# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreisDB\ehpcalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EHPCalc(object):
    def setupUi(self, EHPCalc):
        EHPCalc.setObjectName("EHPCalc")
        EHPCalc.resize(1087, 602)
        EHPCalc.setMinimumSize(QtCore.QSize(730, 600))
        EHPCalc.setMaximumSize(QtCore.QSize(16777215, 16777215))
        EHPCalc.setStyleSheet("*{\n"
"    font-family:segoe ui;\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"    background: yellow;\n"
"    width: 10px; /* when vertical */\n"
"    height: 10px; /* when horizontal */\n"
"}\n"
"\n"
"QWidget#centralwidget{\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QMenuBar{\n"
"    font-size:12px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"QMenu{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"    color: #000000;\n"
"    background-color: #d0d6da;\n"
"    border-style: none;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius: 5px;\n"
"    background-color: rgb(115, 127, 133);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"    width: 20px;\n"
"    border-style: 0px solid;\n"
"    border-radius: 1px;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"    width: 20px;\n"
"    border-style: solid;\n"
"    border-radius: 1px;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/up-arrow.png\');\n"
"    width: 7px;\n"
"    height: 7px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 7px;\n"
"    height: 7px;\n"
"}\n"
"\n"
"QLabel#lblTitle {\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QDateEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background: #d0d6da;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView:enabled {\n"
"    color: #000000;\n"
"    background: #e7eaec;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_navigationbar {\n"
"    color: #000000;\n"
"    background-color: #b8c0c6;\n"
"}\n"
"\n"
"\n"
"QTableView {\n"
"    font-size:12px;\n"
"    background: #ffffff;\n"
"    border-style: none;\n"
"    gridline-color: #737f86;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    color: #000000;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #b8c0c6;\n"
"    padding: 2px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #737f86;\n"
"    border-right: 1px solid #737f86;    \n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #737f86;\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border-left: 1px solid #737f86;\n"
"    border-right: 1px solid #737f86;\n"
"}\n"
"\n"
"\n"
"QListView{\n"
"    font-size:12px;\n"
"    color: #000000;\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListView::item \n"
"{\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QListView::item:hover \n"
"{\n"
"    background-color: #d0d6da;\n"
"    margin: 0px;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*STYLESHEET FÜR QFrame*/\n"
"\n"
"QFrame#fraSideMenu, QFrame#fraTable, QFrame#fraTitle, QFrame#fraFooter {\n"
"    border-radius: 20px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QGridLayout*/\n"
"\n"
"QGridLayout {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QLabel*/\n"
"\n"
"QLabel {\n"
"    border-radius: 0px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QComboBox*/\n"
"\n"
"QComboBox {\n"
"    font-size:12px;\n"
"    border: solid;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background: #d0d6da;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on {\n"
"    background:#a1abb1;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 0px;\n"
"    background: #ffffff;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(EHPCalc)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fraFooter = QtWidgets.QFrame(self.centralwidget)
        self.fraFooter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraFooter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraFooter.setObjectName("fraFooter")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.fraFooter)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lblLabel11 = QtWidgets.QLabel(self.fraFooter)
        self.lblLabel11.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.lblLabel11.setFont(font)
        self.lblLabel11.setObjectName("lblLabel11")
        self.gridLayout_9.addWidget(self.lblLabel11, 0, 0, 1, 1)
        self.lblProgrammname = QtWidgets.QLabel(self.fraFooter)
        self.lblProgrammname.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblProgrammname.setFont(font)
        self.lblProgrammname.setObjectName("lblProgrammname")
        self.gridLayout_9.addWidget(self.lblProgrammname, 0, 1, 1, 1)
        self.lblLabel12 = QtWidgets.QLabel(self.fraFooter)
        self.lblLabel12.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.lblLabel12.setFont(font)
        self.lblLabel12.setObjectName("lblLabel12")
        self.gridLayout_9.addWidget(self.lblLabel12, 1, 0, 1, 1)
        self.lblVersion = QtWidgets.QLabel(self.fraFooter)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblVersion.setFont(font)
        self.lblVersion.setObjectName("lblVersion")
        self.gridLayout_9.addWidget(self.lblVersion, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraFooter, 2, 0, 1, 2)
        self.fraTitle = QtWidgets.QFrame(self.centralwidget)
        self.fraTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTitle.setObjectName("fraTitle")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.fraTitle)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblTitle = QtWidgets.QLabel(self.fraTitle)
        self.lblTitle.setMinimumSize(QtCore.QSize(200, 30))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("")
        self.lblTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout_7.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraTitle, 0, 0, 1, 2)
        self.fraTable = QtWidgets.QFrame(self.centralwidget)
        self.fraTable.setMinimumSize(QtCore.QSize(400, 300))
        self.fraTable.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.fraTable.setObjectName("fraTable")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fraTable)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cmdDetail = QtWidgets.QPushButton(self.fraTable)
        self.cmdDetail.setMinimumSize(QtCore.QSize(145, 25))
        self.cmdDetail.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdDetail.setFont(font)
        self.cmdDetail.setStyleSheet("")
        self.cmdDetail.setObjectName("cmdDetail")
        self.gridLayout_4.addWidget(self.cmdDetail, 3, 4, 1, 1)
        self.grdEHP = QtWidgets.QTableWidget(self.fraTable)
        self.grdEHP.setMinimumSize(QtCore.QSize(400, 300))
        self.grdEHP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.grdEHP.setFont(font)
        self.grdEHP.setAutoFillBackground(False)
        self.grdEHP.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.grdEHP.setLineWidth(0)
        self.grdEHP.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.grdEHP.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.grdEHP.setRowCount(0)
        self.grdEHP.setColumnCount(0)
        self.grdEHP.setObjectName("grdEHP")
        self.grdEHP.horizontalHeader().setCascadingSectionResizes(True)
        self.grdEHP.horizontalHeader().setMinimumSectionSize(20)
        self.grdEHP.horizontalHeader().setSortIndicatorShown(True)
        self.grdEHP.horizontalHeader().setStretchLastSection(True)
        self.grdEHP.verticalHeader().setVisible(False)
        self.grdEHP.verticalHeader().setDefaultSectionSize(20)
        self.grdEHP.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_4.addWidget(self.grdEHP, 2, 0, 1, 6)
        self.txtSearchPos = QtWidgets.QLineEdit(self.fraTable)
        self.txtSearchPos.setMinimumSize(QtCore.QSize(150, 25))
        self.txtSearchPos.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.txtSearchPos.setFont(font)
        self.txtSearchPos.setObjectName("txtSearchPos")
        self.gridLayout_4.addWidget(self.txtSearchPos, 1, 0, 1, 1)
        self.cmdNewPos = QtWidgets.QPushButton(self.fraTable)
        self.cmdNewPos.setMinimumSize(QtCore.QSize(145, 25))
        self.cmdNewPos.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdNewPos.setFont(font)
        self.cmdNewPos.setStyleSheet("")
        self.cmdNewPos.setObjectName("cmdNewPos")
        self.gridLayout_4.addWidget(self.cmdNewPos, 3, 5, 1, 1)
        self.cmdDelete = QtWidgets.QPushButton(self.fraTable)
        self.cmdDelete.setMinimumSize(QtCore.QSize(145, 25))
        self.cmdDelete.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdDelete.setFont(font)
        self.cmdDelete.setStyleSheet("")
        self.cmdDelete.setObjectName("cmdDelete")
        self.gridLayout_4.addWidget(self.cmdDelete, 3, 3, 1, 1)
        self.cmdStartQuery = QtWidgets.QPushButton(self.fraTable)
        self.cmdStartQuery.setMinimumSize(QtCore.QSize(145, 25))
        self.cmdStartQuery.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdStartQuery.setFont(font)
        self.cmdStartQuery.setStyleSheet("")
        self.cmdStartQuery.setObjectName("cmdStartQuery")
        self.gridLayout_4.addWidget(self.cmdStartQuery, 1, 5, 1, 1)
        self.lblLabel4_2 = QtWidgets.QLabel(self.fraTable)
        self.lblLabel4_2.setMinimumSize(QtCore.QSize(150, 20))
        self.lblLabel4_2.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel4_2.setFont(font)
        self.lblLabel4_2.setObjectName("lblLabel4_2")
        self.gridLayout_4.addWidget(self.lblLabel4_2, 0, 1, 1, 1)
        self.lblLabel1 = QtWidgets.QLabel(self.fraTable)
        self.lblLabel1.setMinimumSize(QtCore.QSize(0, 20))
        self.lblLabel1.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel1.setFont(font)
        self.lblLabel1.setToolTipDuration(0)
        self.lblLabel1.setObjectName("lblLabel1")
        self.gridLayout_4.addWidget(self.lblLabel1, 0, 0, 1, 1)
        self.cboLG = QtWidgets.QComboBox(self.fraTable)
        self.cboLG.setMinimumSize(QtCore.QSize(111, 25))
        self.cboLG.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cboLG.setFont(font)
        self.cboLG.setStyleSheet("")
        self.cboLG.setEditable(False)
        self.cboLG.setObjectName("cboLG")
        self.gridLayout_4.addWidget(self.cboLG, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 2, 1, 3)
        self.cmdExport = QtWidgets.QPushButton(self.fraTable)
        self.cmdExport.setMinimumSize(QtCore.QSize(145, 25))
        self.cmdExport.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdExport.setFont(font)
        self.cmdExport.setStyleSheet("")
        self.cmdExport.setObjectName("cmdExport")
        self.gridLayout_4.addWidget(self.cmdExport, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraTable, 1, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        EHPCalc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EHPCalc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 21))
        self.menubar.setObjectName("menubar")
        EHPCalc.setMenuBar(self.menubar)

        self.retranslateUi(EHPCalc)
        QtCore.QMetaObject.connectSlotsByName(EHPCalc)

    def retranslateUi(self, EHPCalc):
        _translate = QtCore.QCoreApplication.translate
        EHPCalc.setWindowTitle(_translate("EHPCalc", "MainWindow"))
        self.lblLabel11.setText(_translate("EHPCalc", "Programmname:"))
        self.lblProgrammname.setText(_translate("EHPCalc", "Version"))
        self.lblLabel12.setText(_translate("EHPCalc", "Version:"))
        self.lblVersion.setText(_translate("EHPCalc", "Version"))
        self.lblTitle.setText(_translate("EHPCalc", "Dateiname"))
        self.cmdDetail.setText(_translate("EHPCalc", "Details / Bearbeiten"))
        self.grdEHP.setSortingEnabled(True)
        self.cmdNewPos.setText(_translate("EHPCalc", "Neue Position"))
        self.cmdDelete.setText(_translate("EHPCalc", "Löschen"))
        self.cmdStartQuery.setText(_translate("EHPCalc", "Suche"))
        self.lblLabel4_2.setText(_translate("EHPCalc", "LG-Suche:"))
        self.lblLabel1.setToolTip(_translate("EHPCalc", "<html><head/><body><p>Durch das setzen von &quot;/&quot; können mehrere Teilbegriffe gesucht werden.</p></body></html>"))
        self.lblLabel1.setText(_translate("EHPCalc", "Positionssuche:"))
        self.cmdExport.setText(_translate("EHPCalc", "Export Excel"))
