# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreisDB\indexrechner.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndexRechner(object):
    def setupUi(self, IndexRechner):
        IndexRechner.setObjectName("IndexRechner")
        IndexRechner.resize(360, 415)
        IndexRechner.setMinimumSize(QtCore.QSize(360, 415))
        IndexRechner.setMaximumSize(QtCore.QSize(360, 415))
        IndexRechner.setStyleSheet("*{\n"
"    font-family:segoe ui;\n"
"    font-size:12px;\n"
"}\n"
"QFrame#fraMain{\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QMenuBar{\n"
"    font-size:12px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"QMenu{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QDateEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background: #d0d6da;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView:enabled {\n"
"    color: #000000;\n"
"    background: #e7eaec;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_navigationbar {\n"
"    color: #000000;\n"
"    background-color: #b8c0c6;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QFrame*/\n"
"\n"
"QFrame#fraPreissteigerung, QFrame#fraBerechnung, QFrame#fraImport {\n"
"    border-radius: 20px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QLabel*/\n"
"\n"
"QLabel {\n"
"    border-radius: 0px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(IndexRechner)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.fraMain = QtWidgets.QFrame(IndexRechner)
        self.fraMain.setObjectName("fraMain")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fraMain)
        self.gridLayout_5.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fraBerechnung = QtWidgets.QFrame(self.fraMain)
        self.fraBerechnung.setMinimumSize(QtCore.QSize(340, 85))
        self.fraBerechnung.setMaximumSize(QtCore.QSize(500, 85))
        self.fraBerechnung.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraBerechnung.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraBerechnung.setObjectName("fraBerechnung")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fraBerechnung)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblLabel5_2 = QtWidgets.QLabel(self.fraBerechnung)
        self.lblLabel5_2.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel5_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel5_2.setFont(font)
        self.lblLabel5_2.setObjectName("lblLabel5_2")
        self.gridLayout_3.addWidget(self.lblLabel5_2, 0, 0, 1, 1)
        self.lblLabel6_2 = QtWidgets.QLabel(self.fraBerechnung)
        self.lblLabel6_2.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel6_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel6_2.setFont(font)
        self.lblLabel6_2.setObjectName("lblLabel6_2")
        self.gridLayout_3.addWidget(self.lblLabel6_2, 0, 1, 1, 1)
        self.lblLabel6_4 = QtWidgets.QLabel(self.fraBerechnung)
        self.lblLabel6_4.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel6_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel6_4.setFont(font)
        self.lblLabel6_4.setObjectName("lblLabel6_4")
        self.gridLayout_3.addWidget(self.lblLabel6_4, 0, 2, 1, 1)
        self.lblIndexVon = QtWidgets.QLabel(self.fraBerechnung)
        self.lblIndexVon.setMinimumSize(QtCore.QSize(100, 20))
        self.lblIndexVon.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblIndexVon.setFont(font)
        self.lblIndexVon.setObjectName("lblIndexVon")
        self.gridLayout_3.addWidget(self.lblIndexVon, 1, 0, 1, 1)
        self.lblIndexBis = QtWidgets.QLabel(self.fraBerechnung)
        self.lblIndexBis.setMinimumSize(QtCore.QSize(100, 20))
        self.lblIndexBis.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblIndexBis.setFont(font)
        self.lblIndexBis.setObjectName("lblIndexBis")
        self.gridLayout_3.addWidget(self.lblIndexBis, 1, 1, 1, 1)
        self.lblPreissteigerung = QtWidgets.QLabel(self.fraBerechnung)
        self.lblPreissteigerung.setMinimumSize(QtCore.QSize(100, 20))
        self.lblPreissteigerung.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblPreissteigerung.setFont(font)
        self.lblPreissteigerung.setObjectName("lblPreissteigerung")
        self.gridLayout_3.addWidget(self.lblPreissteigerung, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.fraBerechnung, 2, 0, 1, 2)
        self.fraPreissteigerung = QtWidgets.QFrame(self.fraMain)
        self.fraPreissteigerung.setMinimumSize(QtCore.QSize(340, 85))
        self.fraPreissteigerung.setMaximumSize(QtCore.QSize(500, 85))
        self.fraPreissteigerung.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraPreissteigerung.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraPreissteigerung.setObjectName("fraPreissteigerung")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fraPreissteigerung)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.datIndexBis = QtWidgets.QDateEdit(self.fraPreissteigerung)
        self.datIndexBis.setMinimumSize(QtCore.QSize(100, 20))
        self.datIndexBis.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.datIndexBis.setFont(font)
        self.datIndexBis.setCalendarPopup(True)
        self.datIndexBis.setObjectName("datIndexBis")
        self.gridLayout_2.addWidget(self.datIndexBis, 1, 1, 1, 1)
        self.lblLabel6 = QtWidgets.QLabel(self.fraPreissteigerung)
        self.lblLabel6.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel6.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel6.setFont(font)
        self.lblLabel6.setObjectName("lblLabel6")
        self.gridLayout_2.addWidget(self.lblLabel6, 0, 1, 1, 1)
        self.cmdRefresh = QtWidgets.QPushButton(self.fraPreissteigerung)
        self.cmdRefresh.setMinimumSize(QtCore.QSize(100, 20))
        self.cmdRefresh.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cmdRefresh.setFont(font)
        self.cmdRefresh.setIconSize(QtCore.QSize(16, 16))
        self.cmdRefresh.setObjectName("cmdRefresh")
        self.gridLayout_2.addWidget(self.cmdRefresh, 0, 2, 1, 1)
        self.lblLabel5 = QtWidgets.QLabel(self.fraPreissteigerung)
        self.lblLabel5.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel5.setFont(font)
        self.lblLabel5.setObjectName("lblLabel5")
        self.gridLayout_2.addWidget(self.lblLabel5, 0, 0, 1, 1)
        self.datIndexVon = QtWidgets.QDateEdit(self.fraPreissteigerung)
        self.datIndexVon.setMinimumSize(QtCore.QSize(100, 20))
        self.datIndexVon.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.datIndexVon.setFont(font)
        self.datIndexVon.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.datIndexVon.setCalendarPopup(True)
        self.datIndexVon.setObjectName("datIndexVon")
        self.gridLayout_2.addWidget(self.datIndexVon, 1, 0, 1, 1)
        self.cmdCalc = QtWidgets.QPushButton(self.fraPreissteigerung)
        self.cmdCalc.setMinimumSize(QtCore.QSize(100, 20))
        self.cmdCalc.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cmdCalc.setFont(font)
        self.cmdCalc.setIconSize(QtCore.QSize(16, 16))
        self.cmdCalc.setObjectName("cmdCalc")
        self.gridLayout_2.addWidget(self.cmdCalc, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.fraPreissteigerung, 1, 0, 1, 2)
        self.fraImport = QtWidgets.QFrame(self.fraMain)
        self.fraImport.setMinimumSize(QtCore.QSize(340, 200))
        self.fraImport.setMaximumSize(QtCore.QSize(340, 200))
        self.fraImport.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraImport.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraImport.setObjectName("fraImport")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fraImport)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblBilligstVAL = QtWidgets.QLabel(self.fraImport)
        self.lblBilligstVAL.setMinimumSize(QtCore.QSize(100, 20))
        self.lblBilligstVAL.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblBilligstVAL.setFont(font)
        self.lblBilligstVAL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBilligstVAL.setObjectName("lblBilligstVAL")
        self.gridLayout_4.addWidget(self.lblBilligstVAL, 3, 2, 1, 1)
        self.lblBilligst = QtWidgets.QLabel(self.fraImport)
        self.lblBilligst.setMinimumSize(QtCore.QSize(100, 20))
        self.lblBilligst.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblBilligst.setFont(font)
        self.lblBilligst.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBilligst.setObjectName("lblBilligst")
        self.gridLayout_4.addWidget(self.lblBilligst, 3, 1, 1, 1)
        self.lblMittelwert = QtWidgets.QLabel(self.fraImport)
        self.lblMittelwert.setMinimumSize(QtCore.QSize(100, 20))
        self.lblMittelwert.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblMittelwert.setFont(font)
        self.lblMittelwert.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMittelwert.setObjectName("lblMittelwert")
        self.gridLayout_4.addWidget(self.lblMittelwert, 1, 1, 1, 1)
        self.lblMedian = QtWidgets.QLabel(self.fraImport)
        self.lblMedian.setMinimumSize(QtCore.QSize(100, 20))
        self.lblMedian.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblMedian.setFont(font)
        self.lblMedian.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMedian.setObjectName("lblMedian")
        self.gridLayout_4.addWidget(self.lblMedian, 4, 1, 1, 1)
        self.cmdImport = QtWidgets.QPushButton(self.fraImport)
        self.cmdImport.setMinimumSize(QtCore.QSize(100, 20))
        self.cmdImport.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cmdImport.setFont(font)
        self.cmdImport.setIconSize(QtCore.QSize(16, 16))
        self.cmdImport.setObjectName("cmdImport")
        self.gridLayout_4.addWidget(self.cmdImport, 0, 2, 1, 1)
        self.lblLabel5_7 = QtWidgets.QLabel(self.fraImport)
        self.lblLabel5_7.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel5_7.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel5_7.setFont(font)
        self.lblLabel5_7.setObjectName("lblLabel5_7")
        self.gridLayout_4.addWidget(self.lblLabel5_7, 4, 0, 1, 1)
        self.lbl3BestVAL = QtWidgets.QLabel(self.fraImport)
        self.lbl3BestVAL.setMinimumSize(QtCore.QSize(100, 20))
        self.lbl3BestVAL.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lbl3BestVAL.setFont(font)
        self.lbl3BestVAL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl3BestVAL.setObjectName("lbl3BestVAL")
        self.gridLayout_4.addWidget(self.lbl3BestVAL, 2, 2, 1, 1)
        self.lblLabel5_6 = QtWidgets.QLabel(self.fraImport)
        self.lblLabel5_6.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel5_6.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel5_6.setFont(font)
        self.lblLabel5_6.setObjectName("lblLabel5_6")
        self.gridLayout_4.addWidget(self.lblLabel5_6, 3, 0, 1, 1)
        self.lblLabel5_3 = QtWidgets.QLabel(self.fraImport)
        self.lblLabel5_3.setMinimumSize(QtCore.QSize(200, 20))
        self.lblLabel5_3.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel5_3.setFont(font)
        self.lblLabel5_3.setObjectName("lblLabel5_3")
        self.gridLayout_4.addWidget(self.lblLabel5_3, 0, 0, 1, 2)
        self.lbl3Best = QtWidgets.QLabel(self.fraImport)
        self.lbl3Best.setMinimumSize(QtCore.QSize(100, 20))
        self.lbl3Best.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lbl3Best.setFont(font)
        self.lbl3Best.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl3Best.setObjectName("lbl3Best")
        self.gridLayout_4.addWidget(self.lbl3Best, 2, 1, 1, 1)
        self.lblLabel5_4 = QtWidgets.QLabel(self.fraImport)
        self.lblLabel5_4.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel5_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel5_4.setFont(font)
        self.lblLabel5_4.setObjectName("lblLabel5_4")
        self.gridLayout_4.addWidget(self.lblLabel5_4, 1, 0, 1, 1)
        self.lblMittelwertVAL = QtWidgets.QLabel(self.fraImport)
        self.lblMittelwertVAL.setMinimumSize(QtCore.QSize(100, 20))
        self.lblMittelwertVAL.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblMittelwertVAL.setFont(font)
        self.lblMittelwertVAL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMittelwertVAL.setObjectName("lblMittelwertVAL")
        self.gridLayout_4.addWidget(self.lblMittelwertVAL, 1, 2, 1, 1)
        self.lblLabel5_5 = QtWidgets.QLabel(self.fraImport)
        self.lblLabel5_5.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLabel5_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel5_5.setFont(font)
        self.lblLabel5_5.setObjectName("lblLabel5_5")
        self.gridLayout_4.addWidget(self.lblLabel5_5, 2, 0, 1, 1)
        self.lblMedianVAL = QtWidgets.QLabel(self.fraImport)
        self.lblMedianVAL.setMinimumSize(QtCore.QSize(100, 20))
        self.lblMedianVAL.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblMedianVAL.setFont(font)
        self.lblMedianVAL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMedianVAL.setObjectName("lblMedianVAL")
        self.gridLayout_4.addWidget(self.lblMedianVAL, 4, 2, 1, 1)
        self.gridLayout_5.addWidget(self.fraImport, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.fraMain, 0, 0, 1, 1)

        self.retranslateUi(IndexRechner)
        QtCore.QMetaObject.connectSlotsByName(IndexRechner)

    def retranslateUi(self, IndexRechner):
        _translate = QtCore.QCoreApplication.translate
        IndexRechner.setWindowTitle(_translate("IndexRechner", "Dialog"))
        self.lblLabel5_2.setText(_translate("IndexRechner", "Indexwert:"))
        self.lblLabel6_2.setText(_translate("IndexRechner", "Indexwert:"))
        self.lblLabel6_4.setText(_translate("IndexRechner", "Preissteigerung:"))
        self.lblIndexVon.setText(_translate("IndexRechner", "-"))
        self.lblIndexBis.setText(_translate("IndexRechner", "-"))
        self.lblPreissteigerung.setText(_translate("IndexRechner", "-"))
        self.lblLabel6.setText(_translate("IndexRechner", "Preisbasis bis:"))
        self.cmdRefresh.setText(_translate("IndexRechner", "Zurücksetzen"))
        self.lblLabel5.setText(_translate("IndexRechner", "Preisbasis von:"))
        self.cmdCalc.setText(_translate("IndexRechner", "Berechnen"))
        self.lblBilligstVAL.setText(_translate("IndexRechner", "0,00"))
        self.lblBilligst.setText(_translate("IndexRechner", "0,00"))
        self.lblMittelwert.setText(_translate("IndexRechner", "0,00"))
        self.lblMedian.setText(_translate("IndexRechner", "0,00"))
        self.cmdImport.setText(_translate("IndexRechner", "Import"))
        self.lblLabel5_7.setText(_translate("IndexRechner", "Median:"))
        self.lbl3BestVAL.setText(_translate("IndexRechner", "0,00"))
        self.lblLabel5_6.setText(_translate("IndexRechner", "Billigstbieter:"))
        self.lblLabel5_3.setText(_translate("IndexRechner", "Importierter Preis [€]:"))
        self.lbl3Best.setText(_translate("IndexRechner", "0,00"))
        self.lblLabel5_4.setText(_translate("IndexRechner", "Mittelwert:"))
        self.lblMittelwertVAL.setText(_translate("IndexRechner", "0,00"))
        self.lblLabel5_5.setText(_translate("IndexRechner", "3 Bestbieter:"))
        self.lblMedianVAL.setText(_translate("IndexRechner", "0,00"))
