# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreisDB\lvposdetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LVPosDetail(object):
    def setupUi(self, LVPosDetail):
        LVPosDetail.setObjectName("LVPosDetail")
        LVPosDetail.resize(1116, 814)
        LVPosDetail.setStyleSheet("*{\n"
"    font-family:segoe ui;\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"    background: yellow;\n"
"    width: 10px; /* when vertical */\n"
"    height: 10px; /* when horizontal */\n"
"}\n"
"\n"
"QWidget#centralwidget{\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QMenuBar{\n"
"    font-size:12px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"QMenu{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"    color: #000000;\n"
"    background-color: #d0d6da;\n"
"    border-style: none;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius: 5px;\n"
"    background-color: rgb(115, 127, 133);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"    width: 20px;\n"
"    border-style: 0px solid;\n"
"    border-radius: 1px;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"    width: 20px;\n"
"    border-style: solid;\n"
"    border-radius: 1px;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/up-arrow.png\');\n"
"    width: 7px;\n"
"    height: 7px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 7px;\n"
"    height: 7px;\n"
"}\n"
"\n"
"QLabel#lblTitle {\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QDateEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background: #d0d6da;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView:enabled {\n"
"    color: #000000;\n"
"    background: #e7eaec;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_navigationbar {\n"
"    color: #000000;\n"
"    background-color: #b8c0c6;\n"
"}\n"
"\n"
"\n"
"QTableView {\n"
"    font-size:12px;\n"
"    background: #ffffff;\n"
"    border-style: none;\n"
"    gridline-color: #737f86;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    color: #000000;\n"
"    background: #d0d6da;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #b8c0c6;\n"
"    padding: 2px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #737f86;\n"
"    border-right: 1px solid #737f86;    \n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #737f86;\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border-left: 1px solid #737f86;\n"
"    border-right: 1px solid #737f86;\n"
"}\n"
"\n"
"\n"
"QListView{\n"
"    font-size:12px;\n"
"    color: #000000;\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListView::item \n"
"{\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #d0d6da;\n"
"    border-radius: 2px;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QListView::item:hover \n"
"{\n"
"    background-color: #d0d6da;\n"
"    margin: 0px;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*STYLESHEET FÜR QFrame*/\n"
"\n"
"QFrame#fraSideMenu, QFrame#fraTable, QFrame#fraTitle, QFrame#fraTabs, QFrame#fraInfo {\n"
"    border-radius: 20px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QGridLayout*/\n"
"\n"
"QGridLayout {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QLabel*/\n"
"\n"
"QLabel {\n"
"    border-radius: 0px;\n"
"    background: #e7eaec;\n"
"}\n"
"\n"
"/*STYLESHEET FÜR QComboBox*/\n"
"\n"
"QComboBox {\n"
"    font-size:12px;\n"
"    border: solid;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background: #d0d6da;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on {\n"
"    background:#a1abb1;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 0px;\n"
"    background: #ffffff;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid black;\n"
"    background: white;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: silver;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #999;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(LVPosDetail)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fraTabs = QtWidgets.QFrame(self.centralwidget)
        self.fraTabs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTabs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTabs.setObjectName("fraTabs")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.fraTabs)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tabWidget = QtWidgets.QTabWidget(self.fraTabs)
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 600))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblLangtextLVPos = QtWidgets.QLabel(self.tab)
        self.lblLangtextLVPos.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLangtextLVPos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblLangtextLVPos.setFont(font)
        self.lblLangtextLVPos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblLangtextLVPos.setWordWrap(True)
        self.lblLangtextLVPos.setObjectName("lblLangtextLVPos")
        self.gridLayout_2.addWidget(self.lblLangtextLVPos, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblLangtextULG = QtWidgets.QLabel(self.tab_2)
        self.lblLangtextULG.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLangtextULG.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblLangtextULG.setFont(font)
        self.lblLangtextULG.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblLangtextULG.setWordWrap(True)
        self.lblLangtextULG.setObjectName("lblLangtextULG")
        self.gridLayout_3.addWidget(self.lblLangtextULG, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lblLangtextLG = QtWidgets.QLabel(self.tab_3)
        self.lblLangtextLG.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLangtextLG.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblLangtextLG.setFont(font)
        self.lblLangtextLG.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblLangtextLG.setWordWrap(True)
        self.lblLangtextLG.setObjectName("lblLangtextLG")
        self.gridLayout_6.addWidget(self.lblLangtextLG, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_15.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraTabs, 2, 0, 1, 1)
        self.fraTable = QtWidgets.QFrame(self.centralwidget)
        self.fraTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTable.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTable.setObjectName("fraTable")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.fraTable)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.grdBieter = QtWidgets.QTableWidget(self.fraTable)
        self.grdBieter.setMinimumSize(QtCore.QSize(450, 450))
        self.grdBieter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.grdBieter.setFont(font)
        self.grdBieter.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.grdBieter.setAutoFillBackground(False)
        self.grdBieter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.grdBieter.setLineWidth(0)
        self.grdBieter.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.grdBieter.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.grdBieter.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.grdBieter.setRowCount(0)
        self.grdBieter.setColumnCount(0)
        self.grdBieter.setObjectName("grdBieter")
        self.grdBieter.horizontalHeader().setCascadingSectionResizes(True)
        self.grdBieter.horizontalHeader().setMinimumSectionSize(20)
        self.grdBieter.horizontalHeader().setSortIndicatorShown(True)
        self.grdBieter.horizontalHeader().setStretchLastSection(False)
        self.grdBieter.verticalHeader().setVisible(False)
        self.grdBieter.verticalHeader().setDefaultSectionSize(20)
        self.grdBieter.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_13.addWidget(self.grdBieter, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraTable, 2, 1, 1, 1)
        self.fraInfo = QtWidgets.QFrame(self.centralwidget)
        self.fraInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraInfo.setObjectName("fraInfo")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.fraInfo)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lblLabel1 = QtWidgets.QLabel(self.fraInfo)
        self.lblLabel1.setMinimumSize(QtCore.QSize(150, 20))
        self.lblLabel1.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel1.setFont(font)
        self.lblLabel1.setToolTipDuration(0)
        self.lblLabel1.setObjectName("lblLabel1")
        self.gridLayout_11.addWidget(self.lblLabel1, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 0, 2, 1, 1)
        self.lblLVPos = QtWidgets.QLabel(self.fraInfo)
        self.lblLVPos.setMinimumSize(QtCore.QSize(100, 20))
        self.lblLVPos.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblLVPos.setFont(font)
        self.lblLVPos.setObjectName("lblLVPos")
        self.gridLayout_11.addWidget(self.lblLVPos, 1, 0, 1, 1)
        self.lblLabel1_2 = QtWidgets.QLabel(self.fraInfo)
        self.lblLabel1_2.setMinimumSize(QtCore.QSize(300, 20))
        self.lblLabel1_2.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel1_2.setFont(font)
        self.lblLabel1_2.setToolTipDuration(0)
        self.lblLabel1_2.setObjectName("lblLabel1_2")
        self.gridLayout_11.addWidget(self.lblLabel1_2, 0, 1, 1, 1)
        self.lblLVposStichwort = QtWidgets.QLabel(self.fraInfo)
        self.lblLVposStichwort.setMinimumSize(QtCore.QSize(300, 20))
        self.lblLVposStichwort.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lblLVposStichwort.setFont(font)
        self.lblLVposStichwort.setObjectName("lblLVposStichwort")
        self.gridLayout_11.addWidget(self.lblLVposStichwort, 1, 1, 1, 1)
        self.lblLabel1_3 = QtWidgets.QLabel(self.fraInfo)
        self.lblLabel1_3.setMinimumSize(QtCore.QSize(145, 20))
        self.lblLabel1_3.setMaximumSize(QtCore.QSize(145, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblLabel1_3.setFont(font)
        self.lblLabel1_3.setToolTipDuration(0)
        self.lblLabel1_3.setObjectName("lblLabel1_3")
        self.gridLayout_11.addWidget(self.lblLabel1_3, 0, 3, 1, 1)
        self.datPBBis = QtWidgets.QDateEdit(self.fraInfo)
        self.datPBBis.setMinimumSize(QtCore.QSize(145, 25))
        self.datPBBis.setMaximumSize(QtCore.QSize(145, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.datPBBis.setFont(font)
        self.datPBBis.setCalendarPopup(True)
        self.datPBBis.setObjectName("datPBBis")
        self.gridLayout_11.addWidget(self.datPBBis, 1, 3, 1, 1)
        self.cmdCalc = QtWidgets.QPushButton(self.fraInfo)
        self.cmdCalc.setMinimumSize(QtCore.QSize(100, 20))
        self.cmdCalc.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cmdCalc.setFont(font)
        self.cmdCalc.setIconSize(QtCore.QSize(16, 16))
        self.cmdCalc.setObjectName("cmdCalc")
        self.gridLayout_11.addWidget(self.cmdCalc, 1, 4, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraInfo, 1, 0, 1, 2)
        self.fraTitle = QtWidgets.QFrame(self.centralwidget)
        self.fraTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTitle.setObjectName("fraTitle")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.fraTitle)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblTitle = QtWidgets.QLabel(self.fraTitle)
        self.lblTitle.setMinimumSize(QtCore.QSize(200, 30))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("")
        self.lblTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout_7.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraTitle, 0, 0, 1, 2)
        self.gridLayout_16.addLayout(self.gridLayout, 0, 0, 1, 1)
        LVPosDetail.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LVPosDetail)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 21))
        self.menubar.setObjectName("menubar")
        LVPosDetail.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LVPosDetail)
        self.statusbar.setObjectName("statusbar")
        LVPosDetail.setStatusBar(self.statusbar)

        self.retranslateUi(LVPosDetail)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LVPosDetail)

    def retranslateUi(self, LVPosDetail):
        _translate = QtCore.QCoreApplication.translate
        LVPosDetail.setWindowTitle(_translate("LVPosDetail", "MainWindow"))
        self.lblLangtextLVPos.setText(_translate("LVPosDetail", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LVPosDetail", "Langtext LV-Pos"))
        self.lblLangtextULG.setText(_translate("LVPosDetail", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LVPosDetail", "Langtext ULG"))
        self.lblLangtextLG.setText(_translate("LVPosDetail", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("LVPosDetail", "Langtext LG"))
        self.grdBieter.setSortingEnabled(True)
        self.lblLabel1.setToolTip(_translate("LVPosDetail", "<html><head/><body><p>Durch das setzen von &quot;/&quot; können mehrere Teilbegriffe gesucht werden.</p></body></html>"))
        self.lblLabel1.setText(_translate("LVPosDetail", "LV-Position"))
        self.lblLVPos.setText(_translate("LVPosDetail", "-"))
        self.lblLabel1_2.setToolTip(_translate("LVPosDetail", "<html><head/><body><p>Durch das setzen von &quot;/&quot; können mehrere Teilbegriffe gesucht werden.</p></body></html>"))
        self.lblLabel1_2.setText(_translate("LVPosDetail", "LV-Positionstichwort"))
        self.lblLVposStichwort.setText(_translate("LVPosDetail", "-"))
        self.lblLabel1_3.setToolTip(_translate("LVPosDetail", "<html><head/><body><p>Durch das setzen von &quot;/&quot; können mehrere Teilbegriffe gesucht werden.</p></body></html>"))
        self.lblLabel1_3.setText(_translate("LVPosDetail", "Preisbasis:"))
        self.cmdCalc.setText(_translate("LVPosDetail", "Berechnen"))
        self.lblTitle.setText(_translate("LVPosDetail", "Dateiname"))
