# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreisDB\testwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestWindow(object):
    def setupUi(self, TestWindow):
        TestWindow.setObjectName("TestWindow")
        TestWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grdView = QtWidgets.QTableView(self.centralwidget)
        self.grdView.setGeometry(QtCore.QRect(260, 20, 300, 291))
        self.grdView.setMinimumSize(QtCore.QSize(300, 0))
        self.grdView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.grdView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.grdView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.grdView.setSortingEnabled(True)
        self.grdView.setObjectName("grdView")
        self.grdView.verticalHeader().setVisible(False)
        TestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        TestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TestWindow)
        self.statusbar.setObjectName("statusbar")
        TestWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TestWindow)
        QtCore.QMetaObject.connectSlotsByName(TestWindow)

    def retranslateUi(self, TestWindow):
        _translate = QtCore.QCoreApplication.translate
        TestWindow.setWindowTitle(_translate("TestWindow", "MainWindow"))
